### ISSUE TITLE
Challenges fail upon clock drift

### ISSUE THREAD

**Issue by ferchault** [NablaChem/hummingqueue#27]
The queries use challenges (timestamps) against replay attacks. In some virtual environments, the clock might drift sufficiently such that challenges fail. Challenges should come from server side, i.e. be server time.

**Comment by ferchault** [comment]
In WSL use `/usr/sbin/ntpdate pool.ntp.org` or restart the distro using `wsl.exe -t <distroname>` as obtained from `wsl.exe -l `

**Comment by Sana-qurishi** [comment]
This cannot be fixed permanently?. or do we have to set it every time, whenever it gives the clock drift error?

**Comment by Sana-qurishi** [comment]
Sometimes the distribution name is different. One can find the exact distribution name with the wsl.exe -l -v command.
